import type { UnitCategory } from './engine';

/**
 * Unit tables. `factor` is the multiplier towards the category base unit.
 * Every factor for imperial/US units is taken from NIST SP 811 exact values.
 */
export const CATEGORIES: readonly UnitCategory[] = [
  {
    id: 'length',
    label: 'Length',
    baseUnit: 'm',
    units: [
      { id: 'nm', label: 'Nanometre', symbol: 'nm', factor: 1e-9 },
      { id: 'um', label: 'Micrometre', symbol: 'µm', factor: 1e-6, aliases: ['micron'] },
      { id: 'mm', label: 'Millimetre', symbol: 'mm', factor: 1e-3 },
      { id: 'cm', label: 'Centimetre', symbol: 'cm', factor: 1e-2 },
      { id: 'm', label: 'Metre', symbol: 'm', factor: 1 },
      { id: 'km', label: 'Kilometre', symbol: 'km', factor: 1000 },
      { id: 'in', label: 'Inch', symbol: 'in', factor: 0.0254, aliases: ['inch', '"'] },
      { id: 'ft', label: 'Foot', symbol: 'ft', factor: 0.3048, aliases: ['foot', "'"] },
      { id: 'yd', label: 'Yard', symbol: 'yd', factor: 0.9144 },
      { id: 'mi', label: 'Mile', symbol: 'mi', factor: 1609.344 },
      { id: 'nmi', label: 'Nautical mile', symbol: 'nmi', factor: 1852 },
      { id: 'au', label: 'Astronomical unit', symbol: 'au', factor: 149597870700 },
      { id: 'ly', label: 'Light year', symbol: 'ly', factor: 9.4607304725808e15 },
      { id: 'pc', label: 'Parsec', symbol: 'pc', factor: 3.0856775814913673e16 },
      { id: 'angstrom', label: 'Ångström', symbol: 'Å', factor: 1e-10 },
    ],
  },
  {
    id: 'area',
    label: 'Area',
    baseUnit: 'm2',
    units: [
      { id: 'mm2', label: 'Square millimetre', symbol: 'mm²', factor: 1e-6 },
      { id: 'cm2', label: 'Square centimetre', symbol: 'cm²', factor: 1e-4 },
      { id: 'm2', label: 'Square metre', symbol: 'm²', factor: 1 },
      { id: 'ha', label: 'Hectare', symbol: 'ha', factor: 10000 },
      { id: 'km2', label: 'Square kilometre', symbol: 'km²', factor: 1e6 },
      { id: 'in2', label: 'Square inch', symbol: 'in²', factor: 0.00064516 },
      { id: 'ft2', label: 'Square foot', symbol: 'ft²', factor: 0.09290304 },
      { id: 'yd2', label: 'Square yard', symbol: 'yd²', factor: 0.83612736 },
      { id: 'acre', label: 'Acre', symbol: 'ac', factor: 4046.8564224 },
      { id: 'mi2', label: 'Square mile', symbol: 'mi²', factor: 2589988.110336 },
    ],
  },
  {
    id: 'volume',
    label: 'Volume',
    baseUnit: 'l',
    units: [
      { id: 'ml', label: 'Millilitre', symbol: 'mL', factor: 1e-3 },
      { id: 'cl', label: 'Centilitre', symbol: 'cL', factor: 1e-2 },
      { id: 'l', label: 'Litre', symbol: 'L', factor: 1, aliases: ['liter'] },
      { id: 'm3', label: 'Cubic metre', symbol: 'm³', factor: 1000 },
      { id: 'cm3', label: 'Cubic centimetre', symbol: 'cm³', factor: 1e-3, aliases: ['cc'] },
      { id: 'in3', label: 'Cubic inch', symbol: 'in³', factor: 0.016387064 },
      { id: 'ft3', label: 'Cubic foot', symbol: 'ft³', factor: 28.316846592 },
      { id: 'gal_us', label: 'US liquid gallon', symbol: 'gal', factor: 3.785411784 },
      { id: 'qt_us', label: 'US liquid quart', symbol: 'qt', factor: 0.946352946 },
      { id: 'pt_us', label: 'US liquid pint', symbol: 'pt', factor: 0.473176473 },
      { id: 'cup_us', label: 'US legal cup', symbol: 'cup', factor: 0.24 },
      { id: 'floz_us', label: 'US fluid ounce', symbol: 'fl oz', factor: 0.0295735295625 },
      { id: 'tbsp', label: 'US tablespoon', symbol: 'tbsp', factor: 0.01478676478125 },
      { id: 'tsp', label: 'US teaspoon', symbol: 'tsp', factor: 0.00492892159375 },
      { id: 'gal_uk', label: 'Imperial gallon', symbol: 'gal (UK)', factor: 4.54609 },
    ],
  },
  {
    id: 'mass',
    label: 'Mass',
    baseUnit: 'kg',
    units: [
      { id: 'ug', label: 'Microgram', symbol: 'µg', factor: 1e-9 },
      { id: 'mg', label: 'Milligram', symbol: 'mg', factor: 1e-6 },
      { id: 'g', label: 'Gram', symbol: 'g', factor: 1e-3 },
      { id: 'kg', label: 'Kilogram', symbol: 'kg', factor: 1 },
      { id: 't', label: 'Tonne', symbol: 't', factor: 1000, aliases: ['metric ton'] },
      { id: 'oz', label: 'Ounce', symbol: 'oz', factor: 0.028349523125 },
      { id: 'lb', label: 'Pound', symbol: 'lb', factor: 0.45359237, aliases: ['pound'] },
      { id: 'stone', label: 'Stone', symbol: 'st', factor: 6.35029318 },
      { id: 'ton_us', label: 'US short ton', symbol: 'ton', factor: 907.18474 },
      { id: 'ton_uk', label: 'Imperial long ton', symbol: 'long ton', factor: 1016.0469088 },
      { id: 'u_amu', label: 'Atomic mass unit', symbol: 'u', factor: 1.66053906660e-27 },
    ],
  },
  {
    id: 'temperature',
    label: 'Temperature',
    baseUnit: 'k',
    units: [
      { id: 'c', label: 'Celsius', symbol: '°C', factor: 1, offset: 273.15 },
      { id: 'f', label: 'Fahrenheit', symbol: '°F', factor: 5 / 9, offset: 255.37222222222223 },
      { id: 'k', label: 'Kelvin', symbol: 'K', factor: 1, offset: 0 },
      { id: 'r', label: 'Rankine', symbol: '°R', factor: 5 / 9, offset: 0 },
      { id: 're', label: 'Réaumur', symbol: '°Ré', factor: 1.25, offset: 273.15 },
    ],
  },
  {
    id: 'time',
    label: 'Time',
    baseUnit: 's',
    units: [
      { id: 'ns', label: 'Nanosecond', symbol: 'ns', factor: 1e-9 },
      { id: 'us', label: 'Microsecond', symbol: 'µs', factor: 1e-6 },
      { id: 'ms', label: 'Millisecond', symbol: 'ms', factor: 1e-3 },
      { id: 's', label: 'Second', symbol: 's', factor: 1 },
      { id: 'min', label: 'Minute', symbol: 'min', factor: 60 },
      { id: 'h', label: 'Hour', symbol: 'h', factor: 3600 },
      { id: 'day', label: 'Day', symbol: 'd', factor: 86400 },
      { id: 'week', label: 'Week', symbol: 'wk', factor: 604800 },
      { id: 'month', label: 'Month (30 days)', symbol: 'mo', factor: 2592000 },
      { id: 'year', label: 'Julian year', symbol: 'a', factor: 31557600 },
    ],
  },
  {
    id: 'speed',
    label: 'Speed',
    baseUnit: 'mps',
    units: [
      { id: 'mps', label: 'Metres per second', symbol: 'm/s', factor: 1 },
      { id: 'kph', label: 'Kilometres per hour', symbol: 'km/h', factor: 1000 / 3600, aliases: ['kmh'] },
      { id: 'mph', label: 'Miles per hour', symbol: 'mph', factor: 0.44704 },
      { id: 'fps', label: 'Feet per second', symbol: 'ft/s', factor: 0.3048 },
      { id: 'knot', label: 'Knot', symbol: 'kn', factor: 1852 / 3600, aliases: ['kts'] },
      { id: 'mach', label: 'Mach (at 15 °C)', symbol: 'Ma', factor: 340.3 },
      { id: 'c_speed', label: 'Speed of light', symbol: 'c', factor: 299792458 },
    ],
  },
  {
    id: 'pressure',
    label: 'Pressure',
    baseUnit: 'pa',
    units: [
      { id: 'pa', label: 'Pascal', symbol: 'Pa', factor: 1 },
      { id: 'hpa', label: 'Hectopascal', symbol: 'hPa', factor: 100, aliases: ['mbar'] },
      { id: 'kpa', label: 'Kilopascal', symbol: 'kPa', factor: 1000 },
      { id: 'mpa', label: 'Megapascal', symbol: 'MPa', factor: 1e6 },
      { id: 'bar', label: 'Bar', symbol: 'bar', factor: 100000 },
      { id: 'atm', label: 'Standard atmosphere', symbol: 'atm', factor: 101325 },
      { id: 'torr', label: 'Torr', symbol: 'Torr', factor: 101325 / 760, aliases: ['mmHg'] },
      { id: 'psi', label: 'Pounds per square inch', symbol: 'psi', factor: 6894.757293168 },
      { id: 'in_hg', label: 'Inch of mercury (0 °C)', symbol: 'inHg', factor: 3386.389 },
      { id: 'kgf_cm2', label: 'Kilogram-force per cm²', symbol: 'kgf/cm²', factor: 98066.5 },
    ],
  },
  {
    id: 'energy',
    label: 'Energy',
    baseUnit: 'j',
    units: [
      { id: 'j', label: 'Joule', symbol: 'J', factor: 1 },
      { id: 'kj', label: 'Kilojoule', symbol: 'kJ', factor: 1000 },
      { id: 'mj', label: 'Megajoule', symbol: 'MJ', factor: 1e6 },
      { id: 'cal', label: 'Calorie (thermochemical)', symbol: 'cal', factor: 4.184 },
      { id: 'kcal', label: 'Kilocalorie', symbol: 'kcal', factor: 4184 },
      { id: 'wh', label: 'Watt-hour', symbol: 'Wh', factor: 3600 },
      { id: 'kwh', label: 'Kilowatt-hour', symbol: 'kWh', factor: 3.6e6 },
      { id: 'ev', label: 'Electronvolt', symbol: 'eV', factor: 1.602176634e-19 },
      { id: 'btu', label: 'British thermal unit (IT)', symbol: 'BTU', factor: 1055.05585262 },
      { id: 'ft_lbf', label: 'Foot-pound force', symbol: 'ft·lbf', factor: 1.3558179483314004 },
      { id: 'tnt', label: 'Tonne of TNT', symbol: 'tTNT', factor: 4.184e9 },
    ],
  },
  {
    id: 'power',
    label: 'Power',
    baseUnit: 'w',
    units: [
      { id: 'mw', label: 'Milliwatt', symbol: 'mW', factor: 1e-3 },
      { id: 'w', label: 'Watt', symbol: 'W', factor: 1 },
      { id: 'kw', label: 'Kilowatt', symbol: 'kW', factor: 1000 },
      { id: 'mw_alt', label: 'Megawatt', symbol: 'MW', factor: 1e6 },
      { id: 'gw', label: 'Gigawatt', symbol: 'GW', factor: 1e9 },
      { id: 'hp_mech', label: 'Horsepower (mechanical)', symbol: 'hp', factor: 745.6998715822702 },
      { id: 'hp_metric', label: 'Horsepower (metric)', symbol: 'PS', factor: 735.49875 },
      { id: 'btu_h', label: 'BTU per hour', symbol: 'BTU/h', factor: 0.29307107017222 },
      { id: 'cal_s', label: 'Calorie per second', symbol: 'cal/s', factor: 4.184 },
    ],
  },
  {
    id: 'data',
    label: 'Data',
    baseUnit: 'b',
    units: [
      { id: 'b', label: 'Bit', symbol: 'b', factor: 1 },
      { id: 'byte', label: 'Byte', symbol: 'B', factor: 8 },
      { id: 'kb', label: 'Kilobit (1000 bit)', symbol: 'kb', factor: 1000 },
      { id: 'kbyte', label: 'Kilobyte (1000 B)', symbol: 'kB', factor: 8000 },
      { id: 'kib', label: 'Kibibit (1024 bit)', symbol: 'Kib', factor: 1024 },
      { id: 'kibyte', label: 'Kibibyte (1024 B)', symbol: 'KiB', factor: 8192 },
      { id: 'mb', label: 'Megabit (10⁶ bit)', symbol: 'Mb', factor: 1e6 },
      { id: 'mbyte', label: 'Megabyte (10⁶ B)', symbol: 'MB', factor: 8e6 },
      { id: 'mibyte', label: 'Mebibyte (1024² B)', symbol: 'MiB', factor: 8388608 },
      { id: 'gbyte', label: 'Gigabyte (10⁹ B)', symbol: 'GB', factor: 8e9 },
      { id: 'gibyte', label: 'Gibibyte (1024³ B)', symbol: 'GiB', factor: 8589934592 },
      { id: 'tbyte', label: 'Terabyte (10¹² B)', symbol: 'TB', factor: 8e12 },
      { id: 'tibyte', label: 'Tebibyte (1024⁴ B)', symbol: 'TiB', factor: 8796093022208 },
    ],
  },
  {
    id: 'frequency',
    label: 'Frequency',
    baseUnit: 'hz',
    units: [
      { id: 'hz', label: 'Hertz', symbol: 'Hz', factor: 1 },
      { id: 'khz', label: 'Kilohertz', symbol: 'kHz', factor: 1000 },
      { id: 'mhz', label: 'Megahertz', symbol: 'MHz', factor: 1e6 },
      { id: 'ghz', label: 'Gigahertz', symbol: 'GHz', factor: 1e9 },
      { id: 'thz', label: 'Terahertz', symbol: 'THz', factor: 1e12 },
      { id: 'rpm', label: 'Revolutions per minute', symbol: 'rpm', factor: 1 / 60 },
    ],
  },
  {
    id: 'angle',
    label: 'Angle',
    baseUnit: 'rad',
    units: [
      { id: 'rad', label: 'Radian', symbol: 'rad', factor: 1 },
      { id: 'deg', label: 'Degree', symbol: '°', factor: Math.PI / 180, aliases: ['degree'] },
      { id: 'grad', label: 'Gradian', symbol: 'gon', factor: Math.PI / 200, aliases: ['gon'] },
      { id: 'turn', label: 'Turn', symbol: 'turn', factor: 2 * Math.PI, aliases: ['rev'] },
      { id: 'arcmin', label: 'Arcminute', symbol: '′', factor: Math.PI / 10800 },
      { id: 'arcsec', label: 'Arcsecond', symbol: '″', factor: Math.PI / 648000 },
      { id: 'mrad', label: 'Milliradian', symbol: 'mrad', factor: 1e-3 },
    ],
  },
];

export function categoryById(id: string): UnitCategory | undefined {
  return CATEGORIES.find((category) => category.id === id);
}
