/**
 * Physical constants in SI units. Values follow the CODATA 2018/2022 adjustments
 * (SI base units were fixed in 2019). Every entry carries its source so a user
 * can verify it — the app never presents an unsourced number as fact.
 */
import type { ConstantDef } from './math';

export const PHYSICAL_CONSTANTS: readonly ConstantDef[] = [
  {
    name: 'c',
    symbol: 'c',
    value: 299792458,
    unit: 'm/s',
    description: 'Speed of light in vacuum (exact by definition of the metre).',
    source: 'CODATA / SI Brochure (2019)',
  },
  {
    name: 'h',
    symbol: 'h',
    value: 6.62607015e-34,
    unit: 'J·s',
    description: 'Planck constant (exact by definition of the kilogram).',
    source: 'CODATA / SI Brochure (2019)',
  },
  {
    name: 'hbar',
    symbol: 'ℏ',
    value: 1.054571817e-34,
    unit: 'J·s',
    description: 'Reduced Planck constant, h/2π.',
    source: 'CODATA 2018',
  },
  {
    name: 'G',
    symbol: 'G',
    value: 6.6743e-11,
    unit: 'm³/(kg·s²)',
    description: 'Newtonian constant of gravitation.',
    source: 'CODATA 2018',
  },
  {
    name: 'e_charge',
    aliases: ['echarge'],
    symbol: 'e',
    value: 1.602176634e-19,
    unit: 'C',
    description: 'Elementary charge (exact). Use e_charge, since e alone is Euler’s number.',
    source: 'CODATA / SI Brochure (2019)',
  },
  {
    name: 'm_e',
    aliases: ['me'],
    symbol: 'mₑ',
    value: 9.1093837015e-31,
    unit: 'kg',
    description: 'Electron rest mass.',
    source: 'CODATA 2018',
  },
  {
    name: 'm_p',
    aliases: ['mp'],
    symbol: 'mₚ',
    value: 1.67262192369e-27,
    unit: 'kg',
    description: 'Proton rest mass.',
    source: 'CODATA 2018',
  },
  {
    name: 'm_n',
    aliases: ['mn'],
    symbol: 'mₙ',
    value: 1.67492749804e-27,
    unit: 'kg',
    description: 'Neutron rest mass.',
    source: 'CODATA 2018',
  },
  {
    name: 'n_a',
    aliases: ['na', 'avogadro'],
    symbol: 'N_A',
    value: 6.02214076e23,
    unit: '1/mol',
    description: 'Avogadro constant (exact).',
    source: 'CODATA / SI Brochure (2019)',
  },
  {
    name: 'k_b',
    aliases: ['kb', 'boltzmann'],
    symbol: 'k_B',
    value: 1.380649e-23,
    unit: 'J/K',
    description: 'Boltzmann constant (exact): relates energy to temperature in kelvin.',
    source: 'CODATA / SI Brochure (2019)',
  },
  {
    name: 'r_gas',
    aliases: ['rgas'],
    symbol: 'R',
    value: 8.314462618,
    unit: 'J/(mol·K)',
    description: 'Molar gas constant, N_A · k_B (ideal gas law).',
    source: 'CODATA 2018',
  },
  {
    name: 'g_0',
    aliases: ['g0', 'g_n'],
    symbol: 'g₀',
    value: 9.80665,
    unit: 'm/s²',
    description: 'Standard acceleration of gravity (exact by definition).',
    source: 'ISO 80000-3 / CGPM',
  },
  {
    name: 'u_amu',
    aliases: ['amu', 'dalton'],
    symbol: 'u',
    value: 1.66053906660e-27,
    unit: 'kg',
    description: 'Atomic mass constant (unified atomic mass unit).',
    source: 'CODATA 2018',
  },
  {
    name: 'epsilon_0',
    aliases: ['epsilon0', 'vacuum_permittivity'],
    symbol: 'ε₀',
    value: 8.8541878128e-12,
    unit: 'F/m',
    description: 'Vacuum electric permittivity.',
    source: 'CODATA 2018',
  },
  {
    name: 'mu_0',
    aliases: ['mu0', 'vacuum_permeability'],
    symbol: 'μ₀',
    value: 1.25663706212e-6,
    unit: 'N/A²',
    description: 'Vacuum magnetic permeability.',
    source: 'CODATA 2018',
  },
  {
    name: 'alpha',
    aliases: ['fine_structure'],
    symbol: 'α',
    value: 7.2973525693e-3,
    unit: '',
    description: 'Fine-structure constant — a dimensionless coupling constant.',
    source: 'CODATA 2018',
  },
  {
    name: 'sigma_sb',
    aliases: ['stefan_boltzmann'],
    symbol: 'σ',
    value: 5.670374419e-8,
    unit: 'W/(m²·K⁴)',
    description: 'Stefan–Boltzmann constant.',
    source: 'CODATA 2018',
  },
  {
    name: 'r_inf',
    aliases: ['rydberg'],
    symbol: 'R∞',
    value: 10973731.56816,
    unit: '1/m',
    description: 'Rydberg constant.',
    source: 'CODATA 2018',
  },
  {
    name: 'f_faraday',
    aliases: ['faraday'],
    symbol: 'F',
    value: 96485.33212,
    unit: 'C/mol',
    description: 'Faraday constant, N_A · e.',
    source: 'CODATA 2018',
  },
  {
    name: 'atm',
    aliases: ['standard_pressure'],
    symbol: 'atm',
    value: 101325,
    unit: 'Pa',
    description: 'Standard atmosphere (exact).',
    source: 'IUPAC',
  },
  {
    name: 'v_molar',
    aliases: ['molar_volume'],
    symbol: 'V_m',
    value: 0.02241396954,
    unit: 'm³/mol',
    description: 'Molar volume of an ideal gas at 273.15 K and 100 kPa.',
    source: 'CODATA 2018',
  },
];
