/** Post-build step: writes dist/sw.js precaching every emitted asset. */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, posix, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const dist = join(root, 'dist');

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(dist)
  .map((file) => relative(dist, file).split(sep).join(posix.sep))
  .filter((file) => file !== 'sw.js' && !file.endsWith('.map'))
  .sort();

const hash = createHash('sha256');
for (const file of files) hash.update(file + ':' + readFileSync(join(dist, file)).length);
const version = hash.digest('hex').slice(0, 12);

const sw = `/* Generated by scripts/build-sw.mjs — do not edit. */
const CACHE = 'omnica-${version}';
const ASSETS = ${JSON.stringify(files, null, 2)};
const INDEX = './index.html';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS.map((file) => new URL(file, self.location).href)))
      .then(() => self.skipWaiting())
      .catch(() => undefined),
  );
});

// The new worker waits until the page asks for it, so the user chooses when to
// reload instead of losing work mid-calculation.
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(fetch(request).catch(() => caches.match(INDEX).then((hit) => hit || Response.error())));
    return;
  }

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => undefined);
        }
        return response;
      }).catch(() => caches.match(INDEX).then((cached) => cached || Response.error()));
    }),
  );
});
`;

writeFileSync(join(dist, 'sw.js'), sw);
console.log(`sw: precached ${files.length} assets as omnica-${version}`);
